language: python

python:
  - "2.7"

sudo: false
cache: pip

git:
  submodules: false

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="7.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: ABaQffZycmzdJs9Slg4OLC8K+wnmpkS5R7bEIOAgsZYMYnOntZz6SzhF8/TOqI2hdUyvxgyVLhUlZdLrgogUgG/V2QjdmIErE6+x4iHECgQ4iXvhqtTpN2S/SVyjVP+7QE8Ugnth/tykWxXpgMpkuA6xnGC2HU8r/s4261tys4g=

  matrix:
  - LINT_CHECK="1"
  # - TRANSIFEX="0"
  - TESTS="0" ODOO_REPO="odoo/odoo"
  - TESTS="0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --depth=1
  - mv ${HOME}/tools/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

install:
  # - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  # - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
